# Generated by Django 5.2 on 2025-04-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_inventory_created_item_created_tag_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('user_name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
    ]
